name: Prueba Token
on: [push]
jobs:
  check-token:
    runs-on: self-hosted
    steps:
      - name: Comparar tokens
        env:
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
        run: |
          $devToken = "$env:DEV_TOKEN"
          $localToken = "$env:LOCAL_DEV_TOKEN"
          
          Write-Output "Iniciando comparacion"
          if ($devToken -eq $localToken) {
              Write-Output "Los tokens coinciden."
          } else {
              Write-Output "Los tokens NO coinciden."
              exit 1
          }
