name: Prueba Token
on: [push]
jobs:
  check-token:
    runs-on: self-hosted
    steps:
      - name: Comparar tokens
        env:
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
        run: |
          if ($env:DEV_TOKEN -eq "$env:LOCAL_DEV_TOKEN") {
              Write-Output "Los tokens coinciden."
              exit 0
          } else {
              Write-Output "Los tokens NO coinciden."
              exit 1
          }
